language: node_js
node_js: "stable"

#cache:
#  directories:
#    - node_modules

dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_install:
  - stty cols 80

before_script:
  - qx lint
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - qx package install
  - ( qx serve --target=build & ) | while read output; do echo "$output"; if [[ $output == *"Web server started"* ]]; then break; fi; done;
  - echo "Starting tests..."

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: compiled/build
  on:
    branch: master
